"""scenario key and art

Revision ID: 19dc621573ef
Revises: a7e7bc0be51e
Create Date: 2026-06-24 21:31:46.541971
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '19dc621573ef'
down_revision: Union[str, None] = 'a7e7bc0be51e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('key', sa.String(length=48), nullable=True))
    op.add_column('scenarios', sa.Column('art', sa.String(length=48), nullable=True))
    op.create_unique_constraint(None, 'scenarios', ['key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scenarios', type_='unique')
    op.drop_column('scenarios', 'art')
    op.drop_column('scenarios', 'key')
    # ### end Alembic commands ###
