"""matchmaking: discoverable + match_waves

Revision ID: 5a4a6c5f118c
Revises: 19dc621573ef
Create Date: 2026-06-25 16:43:19.975517
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5a4a6c5f118c'
down_revision: Union[str, None] = '19dc621573ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_waves',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_user_id', sa.UUID(), nullable=False),
    sa.Column('to_user_id', sa.UUID(), nullable=False),
    sa.Column('from_character_id', sa.UUID(), nullable=False),
    sa.Column('to_character_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_user_id', 'to_user_id', name='uq_wave_pair')
    )
    op.create_index(op.f('ix_match_waves_from_user_id'), 'match_waves', ['from_user_id'], unique=False)
    op.create_index(op.f('ix_match_waves_to_user_id'), 'match_waves', ['to_user_id'], unique=False)
    # server_default backfills existing rows; NOT NULL is then safe.
    op.add_column('users', sa.Column('discoverable', sa.Boolean(),
                                     nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'discoverable')
    op.drop_index(op.f('ix_match_waves_to_user_id'), table_name='match_waves')
    op.drop_index(op.f('ix_match_waves_from_user_id'), table_name='match_waves')
    op.drop_table('match_waves')
    # ### end Alembic commands ###
