"""character friendships

Revision ID: a7e7bc0be51e
Revises: 782ef0db5063
Create Date: 2026-06-24 17:22:22.983714
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a7e7bc0be51e'
down_revision: Union[str, None] = '782ef0db5063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_friendships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_a_id', sa.UUID(), nullable=False),
    sa.Column('character_b_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_a_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_b_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_a_id', 'character_b_id', name='uq_char_friend_pair')
    )
    op.create_index(op.f('ix_character_friendships_character_a_id'), 'character_friendships', ['character_a_id'], unique=False)
    op.create_index(op.f('ix_character_friendships_character_b_id'), 'character_friendships', ['character_b_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_friendships_character_b_id'), table_name='character_friendships')
    op.drop_index(op.f('ix_character_friendships_character_a_id'), table_name='character_friendships')
    op.drop_table('character_friendships')
    # ### end Alembic commands ###
