"""character chats

Revision ID: f1479a29d4b0
Revises: 08ddecf46636
Create Date: 2026-06-25 23:05:09.950110
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f1479a29d4b0'
down_revision: Union[str, None] = '08ddecf46636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_a_id', sa.UUID(), nullable=False),
    sa.Column('character_b_id', sa.UUID(), nullable=False),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_a_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_b_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_chats_character_a_id'), 'character_chats', ['character_a_id'], unique=False)
    op.create_index(op.f('ix_character_chats_character_b_id'), 'character_chats', ['character_b_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_chats_character_b_id'), table_name='character_chats')
    op.drop_index(op.f('ix_character_chats_character_a_id'), table_name='character_chats')
    op.drop_table('character_chats')
    # ### end Alembic commands ###
